{
  "updates": [
    {
      "commit-message": {
        "prefix": "chore(deps)"
      },
      "directory": "/",
      "labels": [
        "dependencies",
        "automated"
      ],
      "open-pull-requests-limit": 20,
      "package-ecosystem": "nix",
      "schedule": {
        "interval": "daily"
      }
    }
  ],
  "version": 2
}
