{
  partitions.dev.module = { config, ... }: {
    text.readme = {
      order = [
        "intro"
        "ci-badge"
        "flakehub"
        "attribution"
        "determinate"
        "development"
        "nixos-configurations"
        "github-actions"
        "files"
      ];

      parts.intro =
        # markdown
        ''
          # ${config.flake.meta.repo.owner}/${config.flake.meta.repo.name}

          ${config.flake.meta.owner.name}'s [Nix](https://nix.dev)-powered system configuration repository.
          Manages NixOS and nix-darwin hosts, home-manager modules, and development environments declaratively.

          > [!NOTE]
          > If you have any questions or suggestions, feel free to use the discussions feature or contact me.

        '';

      parts.determinate =
        # markdown
        ''
          ## Determinate

          Flake inputs track their native upstream repositories.
          macOS is managed by [Determinate Nix](https://determinate.systems),
          which provides a curated Nix installation for darwin systems.

        '';

      parts.development =
        # markdown
        ''
          ## Working on this flake

          `flake.nix` is generated by [flake-file](https://flake-file.denful.dev/).
          Declare inputs beside their features with `flake-file.inputs`; keep explicit
          `follows` declarations and let `flake.lock` pin revisions. Do not edit the
          generated file directly.

          ```sh
          nix run .#write-flake   # Regenerate flake.nix after editing input declarations
          nix flake lock         # Lock added or changed inputs
          nix run .#write-files   # Regenerate README, workflows, and other managed files
          nix fmt
          nix flake check --no-eval-cache --no-build --all-systems
          ```

          Development shells, formatting, generated-file apps, and checks use the
          `dev` flake-parts partition. Host and ordinary package evaluation do not
          import those tooling modules. There is still one shared lockfile;
          `all-check-store-paths` intentionally evaluates the development checks.

          Helix and Zed share flake-aware nixd settings for NixOS, Darwin, the current
          user's Home Manager modules, and development flake-parts options. These
          follow the live checkout configured by `programs.nh.flake` (normally
          `~/rhizome`), not the immutable source of the last system rebuild.

          After rebuilding, use `nix-inspect -p ~/rhizome` to browse evaluated
          configuration and `nix-melt` from this directory to inspect the lockfile.
          `nix-your-shell` keeps Fish in interactive Nix shells; it replaces
          `any-nix-shell` and its package-list right prompt.

          For REPL inspection, run `nix repl` then `:lf .`. Root options are under
          `debug.options`; development options are under
          `debug.partitions.dev.module.flake.debug.options`, with per-system options
          under `debug.partitions.dev.module.flake.allSystems.<system>.options`.

        '';

      parts.attribution =
        # markdown
        ''
          ## Acknowledgements

          > [!IMPORTANT]
          > This repository is heavily inspired by [@mightyiam](https://github.com/mightyiam)'s
          > infrastructure repo. The architecture, patterns, and much of the tooling
          > originate from his work. All praise should go to him.

        '';
    };

    perSystem = {
      files.file."README.md".text = config.text.readme;
    };
  };
}
