{
  "jobs": {
    "check-darwin": {
      "needs": "get-check-names-darwin",
      "runs-on": "macos-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4",
          "with": {
            "submodules": true
          }
        },
        {
          "uses": "DeterminateSystems/nix-installer-action@main"
        },
        {
          "uses": "DeterminateSystems/flakehub-cache-action@main"
        },
        {
          "run": "nix --accept-flake-config build '.#checks.aarch64-darwin.\"${{ matrix.checks }}\"'\n"
        }
      ],
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "checks": "${{ fromJson(needs.get-check-names-darwin.outputs.checks) }}"
        }
      }
    },
    "check-linux": {
      "needs": "get-check-names-linux",
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4",
          "with": {
            "submodules": true
          }
        },
        {
          "uses": "wimpysworld/nothing-but-nix@main",
          "with": {
            "hatchet-protocol": "holster"
          }
        },
        {
          "uses": "DeterminateSystems/nix-installer-action@main"
        },
        {
          "uses": "DeterminateSystems/flakehub-cache-action@main"
        },
        {
          "run": "nix --accept-flake-config build '.#checks.x86_64-linux.\"${{ matrix.checks }}\"'\n"
        }
      ],
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "checks": "${{ fromJson(needs.get-check-names-linux.outputs.checks) }}"
        }
      }
    },
    "flakehub-publish": {
      "if": "github.ref == 'refs/heads/main'",
      "needs": [
        "check-linux",
        "check-darwin"
      ],
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4",
          "with": {
            "submodules": true
          }
        },
        {
          "uses": "DeterminateSystems/nix-installer-action@main"
        },
        {
          "uses": "DeterminateSystems/flakehub-push@main",
          "with": {
            "name": "LilDojd/rhizome",
            "rolling": true,
            "visibility": "public"
          }
        }
      ]
    },
    "get-check-names-darwin": {
      "outputs": {
        "checks": "${{ steps.get-check-names.outputs.checks }}"
      },
      "runs-on": "macos-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4",
          "with": {
            "submodules": true
          }
        },
        {
          "uses": "DeterminateSystems/nix-installer-action@main"
        },
        {
          "uses": "DeterminateSystems/flakehub-cache-action@main"
        },
        {
          "id": "get-check-names",
          "run": "checks=\"$(nix --accept-flake-config eval --json .#checks.aarch64-darwin --apply builtins.attrNames)\"\necho \"checks=$checks\" >> $GITHUB_OUTPUT\n"
        }
      ]
    },
    "get-check-names-linux": {
      "outputs": {
        "checks": "${{ steps.get-check-names.outputs.checks }}"
      },
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v4",
          "with": {
            "submodules": true
          }
        },
        {
          "uses": "DeterminateSystems/nix-installer-action@main"
        },
        {
          "uses": "DeterminateSystems/flakehub-cache-action@main"
        },
        {
          "id": "get-check-names",
          "run": "checks=\"$(nix --accept-flake-config eval --json .#checks.x86_64-linux --apply builtins.attrNames)\"\necho \"checks=$checks\" >> $GITHUB_OUTPUT\n"
        }
      ]
    }
  },
  "name": "Check",
  "on": {
    "push": {},
    "workflow_call": {}
  },
  "permissions": {
    "contents": "read",
    "id-token": "write"
  }
}
